# Generated by Django 5.1.1 on 2024-10-02 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_id', models.UUIDField(default=uuid.uuid4)),
                ('template_type', models.CharField(blank=True, choices=[('default', 'Default'), ('custom', 'Custom')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField()),
                ('link_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('action', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='attacker.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='custom_template_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attacker.template')),
            ],
        ),
    ]
