# Generated by Django 5.1.1 on 2024-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtemplate',
            name='original_template',
        ),
        migrations.RemoveField(
            model_name='customtemplate',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='customtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
