# Generated by Django 5.1.1 on 2024-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacker', '0002_remove_customtemplate_original_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='campaign_attachments/'),
        ),
    ]
