# Generated by Django 5.1.1 on 2024-10-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacker', '0005_linktracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrackinglog',
            name='device_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtrackinglog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linktracking',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
