# Generated by Django 5.1.1 on 2024-10-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacker', '0007_campaign_is_active_campaign_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recurrence_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('seconds', 'Seconds'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
    ]
