# Generated by Django 5.1.1 on 2024-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacker', '0008_campaign_recurrence_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtrackinglog',
            old_name='ip_address',
            new_name='ipv4_address',
        ),
        migrations.AddField(
            model_name='emailtrackinglog',
            name='ipv6_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
