# Generated by Django 5.1.1 on 2024-10-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacker', '0010_remove_emailtrackinglog_ipv4_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrackinglog',
            name='ip_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
